README.md, decks/_empty_deck_template/.gitignore, decks/_empty_deck_template/00-intro.mdx, decks/_empty_deck_template/index.js, decks/_empty_deck_template/package.json, decks/_empty_deck_template/readme.mdx
@renvrant - added some instructions on setting up a new stand-alone deck, and a template folder that you can copy/paste to set the foundation.
Hope it's helpful
=> Instructions on setting up new deck

components/replit.js, decks/functions/02-function-context.mdx, decks/promises/00-promises.mdx, decks/promises/01-promise-chain.mdx, decks/promises/02-promise-errors.mdx, decks/promises/03-promise-patterns.mdx, decks/promises/index.js, decks/promises/snippets/promise-chain-2.snippet, decks/promises/snippets/promise-chain-3.snippet, decks/promises/snippets/promise-chain-4.snippet, decks/promises/snippets/promise-chain.snippet, decks/promises/snippets/promise-errors-1.snippet, decks/promises/snippets/promise-errors-2.snippet, decks/promises/snippets/promise-errors-3.snippet, decks/promises/snippets/promise-errors-4.snippet
* added examples on promise chains
* combining promises
* promise.all
Todo:
=> Added Promise Chains

components/codesandbox.js, decks/react/01-components.mdx, decks/react/02-props.mdx, decks/react/03-composition.mdx, decks/react/index.js, decks/react/snippets/props.snippet, decks/styles/.gitignore, decks/styles/00-intro.mdx, decks/styles/01-css-approaches.mdx, decks/styles/index.js, decks/styles/package.json, decks/styles/readme.mdx, decks/variables/01-variables.mdx, now.json
Looks like using the `<LiveCode` component was causing issues with how  `<CodeSurf>` was loading files.
Moved some examples to CodeSandbox - it gives people a spot to play with them that persists after (instead of being only in the browser)
=> Fix CodeSurf

decks/functions/00-intro.mdx, decks/functions/01-function-scope-closure-context.mdx, decks/functions/02-function-closure.mdx, decks/functions/04-arrow-functions.mdx, decks/functions/05-function-callback.mdx, decks/functions/index.js, decks/functions/snippets/block.1.snippet, decks/functions/snippets/block.2.snippet, decks/functions/snippets/block.snippet, decks/functions/snippets/roughstuff, decks/template-literals/01-intro.mdx
* Had accidentally deleted section with information on `this` added it back
* Fleshed out block scope a bit more
=> Flesh out block scope

decks/arrays/99-array-exercises.mdx, decks/arrays/index.js
@renvrant added two array exercises and solutions to repl.it
=> add two array exercises

decks/variables/01-variables.mdx, decks/variables/02-let.mdx
* Some of the scope examples were creating globals due to lack of strict mode - updated
=> fix: use strict on some runkits

decks/template-literals/01-intro.mdx, decks/template-literals/02-tagged-template.mdx, decks/template-literals/snippets/template-ex-4.snippet
Moved Tagged Template Literals into own deck
Might not cover them - the use cases for them are not that obvious, and end up not being talked about later on in the training.
It is how things like styled components, htm, etc work under the hood.
I did wonder how
```
let Button = styled.a` .....`
```
worked before - but not sure how much value it has spending time on this for this training.
=> Update Template Literals

deck.js, decks/arrays/00-intro.mdx, decks/arrays/package.json, decks/classes/00-intro.mdx, decks/classes/01-subclassing.mdx, decks/destructuring/02-rest.mdx, decks/destructuring/03-spread.mdx, decks/destructuring/package.json, decks/functions/00-intro.mdx, decks/functions/01-pure-functions.mdx, decks/functions/02-arrow-functions.mdx, decks/functions/03-function-callback.mdx, decks/functions/04-function-closure.mdx, decks/functions/05-function-scope-closure-context.mdx, decks/functions/06-function-context-this.mdx, decks/literals/package.json, decks/promises/02-promise-errors.mdx, decks/promises/03-promise-patterns.mdx, decks/react-thinking-in-components/00-intro.mdx, decks/variables/01-variables.mdx, decks/variables/02-let-const.mdx
* Trying to get consistent with having a clear 'opening' slide to help have a visual cue for breaks
* Fixed some examples
Possible running order added in the deck.js
=> Misc Tweaks

components/codesandbox.js, decks/react/00-intro.mdx, decks/react/01-components.mdx, decks/react/02-props.mdx
- Added optional prop to auto-run instead of needing click to run
- Cleaned up some wording
- Changed layout to not use Split in a few spots
- Auto run basic examples
- Broke out Destructuring Props into smaller bullets
=> Misc Cleanup

decks/arrays/00-intro.mdx, decks/arrays/01-iterating.mdx, decks/arrays/99-array-exercises.mdx
* Tried to speak to map / filter / reduce in terms that they might be used to
* Added an 'inline' reduce example to re-write something they might usually use a forLoop for using reduce
* Added a more complex array exercise at the end - it's one that I sort of made up 'ad-hoc' during the first session - part of the deck now
=> Array Deck Changes

decks/functions/00-intro.mdx, decks/functions/04-function-closure.mdx, decks/functions/05-function-scope-context.mdx, decks/functions/index.js
- Since we cover closures before scope and context - clean up file names and order
- Gave another example of a use case for functions returning functions
- Updated index to reflect file name changes
=> Function Cleanup

examples/context-reducer-dispatch/src/App.test.js, examples/fetch-game-list-example-external/src/App.test.js, examples/fetch-game-list-example/src/App.test.js, examples/forms-with-classes/src/App.test.js, examples/forms-with-hooks-refactor/src/App.test.js, examples/forms-with-hooks/src/App.test.js, examples/react-basic-class-component/src/App.test.js, examples/react-data-down-events-up/src/App.test.js, examples/react-list-example-remove-item/src/App.test.js, examples/react-list-example/src/App.test.js, exercises/data-fetch-01-start/src/App.test.js, exercises/data-fetch-02-start/src/App.test.js, exercises/data-fetch-03-start/src/App.test.js, exercises/data-fetch-04-start/src/App.test.js, exercises/events-robbot-list-remove-robot-end/src/App.test.js, exercises/events-robbot-list-remove-robot-start/src/App.test.js, exercises/extracting-components-01-end/src/App.test.js, exercises/extracting-components-01-start/src/App.test.js, exercises/react-events/src/App.test.js, exercises/react-state/src/App.test.js
* Example and Exercise app's are not doingany testing - cleaning up unneeded files
=> Remove App.test.js

exercises/promise-all-end/package.json, exercises/promise-all-end/src/components/App.js, exercises/promise-all-start/package.json, exercises/promise-all-start/src/components/App.js, exercises/promise-all-start/src/exercise-01.js
* compile errors
* type / syntax errors
* promise rejections
Should be better handled in the main App.component and display things properly in the console
=> Improve error handling

README.md
Update Readme for running decks locally #97 
* Added some initial details on project setup
=> Update Readme for running decks locally #97

agenda-04-22-2019.md
Updated agenda content for April 22nd - #101
=> [#101] Update Agenda for April 22nd

decks/arrays/02-iterating.mdx, decks/arrays/99-array-exercises.mdx, decks/react-events-state/03-react-state-and-data-flow.mdx, decks/react-events-state/stateful-component-exercise.mdx, decks/react-props-and-rendering/01-props.mdx, decks/react-props-and-rendering/02-composition.mdx, decks/react-props-and-rendering/03-rendering-lists.mdx, decks/react-props-and-rendering/04-conditional-rendering.mdx, decks/react-props-and-rendering/05-01-exercise-1-media-card.mdx, decks/react-props-and-rendering/05-02-exercise-2-product-card.mdx, decks/template-literals/02-tagged-template.mdx, exercises/react-render-list-01-end/.prettierrc, exercises/react-render-list-01-end/package.json, exercises/react-render-list-01-end/public/index.html, exercises/react-render-list-01-end/sandbox.config.json, exercises/react-render-list-01-end/src/index.js, exercises/react-render-list-01-end/src/styles.css, exercises/react-render-list-01-start/.prettierrc, exercises/react-render-list-01-start/package.json, exercises/react-render-list-01-start/public/index.html, exercises/react-render-list-01-start/sandbox.config.json, exercises/react-render-list-01-start/src/index.js, exercises/react-render-list-01-start/src/styles.css
Make `Exercise` heading consistent
Heading Format
MDX Spacing for ReplIt
update headings
=> Es misc deck cleanup

decks/react-components/01-thinking-in-components.mdx, decks/react-components/02-components.mdx
relates to #105 
- Update text on 'ecosystem' slide to be consistent with previous slides
=> #105 - Update Atomic Slides

decks/react-components/02-components.mdx, decks/react-data-fetching/01-data-fetch.mdx
* Disable eslint for embed
* Use codemirror editor
=> Update DataFetch codesandbox embeds

decks/arrays/01-array-modification-and-mutation.mdx, decks/arrays/02-iterating.mdx, decks/arrays/99-array-exercises.mdx
* Give example of reducer for state management
=> Update Array Content

decks/react-props-and-rendering/snippets/productcard.snippet, exercises/extracting-components-01-end/src/components/ProductCard.js, exercises/extracting-components-01-start/README.md, exercises/extracting-components-01-start/src/App.js
=> fix #122 - change class="..." to className="..."

decks/react-events-state/01-class-based-components.mdx
* Had Editor link not Embed link
=> Fix Embed URL for Cascading Dropdown

decks/promises/01-promise-chain.mdx, decks/promises/01.1-deferred-anti-pattern.mdx
* Kept the slide seperate incase someone does want to go over it
* we don't talk about it after - so dropping it for now
* Had feedback of 'spending too much time on the wrong way to do things' - need to spend more time on the right / recomended way
=> remove deferred example

decks/functions/00-intro.mdx, decks/functions/02-arrow-functions.mdx
* Split some items into own slides to make more clear
* Change arrow-returns into runnable examples
=> Adjust functions deck

decks/react-props-and-rendering/01-props.mdx, examples/react-props-examples/.prettierrc, examples/react-props-examples/package.json, examples/react-props-examples/public/index.html, examples/react-props-examples/sandbox.config.json, examples/react-props-examples/src/ExampleOne.js, examples/react-props-examples/src/ExampleTwo.js, examples/react-props-examples/src/index.js, examples/react-props-examples/src/styles.css, yarn.lock
* explain why of props a bit more
* move one of the examples into repo instead of being managed on git-hub
* moved exercise a bit earlier up
* split out adding prop types to second/optional exercise at the end
=> props update
